"""add admin models

Revision ID: c65ea449dfc3
Revises: ee47a92200be
Create Date: 2026-01-20 14:23:28.719440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65ea449dfc3'
down_revision: Union[str, None] = 'ee47a92200be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值（JSON格式）'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='配置分类：claude/review/performance/advanced'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_settings_category'), 'admin_settings', ['category'], unique=False)
    op.create_index(op.f('ix_admin_settings_key'), 'admin_settings', ['key'], unique=True)
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Gitea 用户名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='用户邮箱'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='角色: super_admin 或 admin'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限配置（JSON格式）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_alias', sa.String(length=100), nullable=False, comment='Key 别名'),
    sa.Column('anthropic_base_url', sa.String(length=500), nullable=True, comment='Anthropic API Base URL'),
    sa.Column('anthropic_auth_token', sa.String(length=500), nullable=False, comment='Anthropic Auth Token（加密存储）'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级（数字越大优先级越高）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('daily_quota', sa.Integer(), nullable=True, comment='每日配额（Token数）'),
    sa.Column('monthly_quota', sa.Integer(), nullable=True, comment='每月配额（Token数）'),
    sa.Column('total_calls', sa.Integer(), nullable=False, comment='总调用次数'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总Token消耗'),
    sa.Column('today_calls', sa.Integer(), nullable=False, comment='今日调用次数'),
    sa.Column('today_tokens', sa.Integer(), nullable=False, comment='今日Token消耗'),
    sa.Column('month_calls', sa.Integer(), nullable=False, comment='本月调用次数'),
    sa.Column('month_tokens', sa.Integer(), nullable=False, comment='本月Token消耗'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_alias'), 'api_keys', ['key_alias'], unique=True)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False, comment='请求ID（用于追踪）'),
    sa.Column('repository_id', sa.Integer(), nullable=False, comment='仓库ID'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型（pull_request/issue_comment）'),
    sa.Column('payload', sa.Text(), nullable=False, comment='完整的Webhook Payload（JSON格式）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态：success/error/retrying'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False, comment='处理耗时（毫秒）'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_event_type'), 'webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_logs_repository_id'), 'webhook_logs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_request_id'), 'webhook_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_webhook_logs_status'), 'webhook_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_status'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_request_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_repository_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_type'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_api_keys_key_alias'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_settings_key'), table_name='admin_settings')
    op.drop_index(op.f('ix_admin_settings_category'), table_name='admin_settings')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
