"""initial

Revision ID: ee47a92200be
Revises: 
Create Date: 2025-12-19 03:37:25.339909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee47a92200be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'repo_name', name='uq_owner_repo')
    )
    op.create_index(op.f('ix_repositories_owner'), 'repositories', ['owner'], unique=False)
    op.create_index(op.f('ix_repositories_repo_name'), 'repositories', ['repo_name'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('default_features', sa.Text(), nullable=True, comment="JSON数组: ['comment', 'review', 'status']"),
    sa.Column('default_focus', sa.Text(), nullable=True, comment="JSON数组: ['quality', 'security', 'performance', 'logic']"),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('anthropic_base_url', sa.String(length=500), nullable=True, comment='Anthropic API Base URL'),
    sa.Column('anthropic_auth_token', sa.String(length=500), nullable=True, comment='Anthropic Auth Token'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_repository_id'), 'model_configs', ['repository_id'], unique=False)
    op.create_table('review_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_title', sa.String(length=500), nullable=True),
    sa.Column('pr_author', sa.String(length=255), nullable=True),
    sa.Column('head_branch', sa.String(length=255), nullable=True),
    sa.Column('base_branch', sa.String(length=255), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('trigger_type', sa.String(length=20), nullable=False, comment='auto / manual'),
    sa.Column('enabled_features', sa.Text(), nullable=True, comment='JSON数组'),
    sa.Column('focus_areas', sa.Text(), nullable=True, comment='JSON数组'),
    sa.Column('analysis_mode', sa.String(length=20), nullable=True, comment='full / simple'),
    sa.Column('diff_size_bytes', sa.Integer(), nullable=True),
    sa.Column('overall_severity', sa.String(length=20), nullable=True, comment='critical / high / medium / low / info'),
    sa.Column('summary_markdown', sa.Text(), nullable=True),
    sa.Column('inline_comments_count', sa.Integer(), nullable=False),
    sa.Column('overall_success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_sessions_pr_number'), 'review_sessions', ['pr_number'], unique=False)
    op.create_index(op.f('ix_review_sessions_repository_id'), 'review_sessions', ['repository_id'], unique=False)
    op.create_table('inline_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_session_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('new_line', sa.Integer(), nullable=True),
    sa.Column('old_line', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='critical / high / medium / low'),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inline_comments_review_session_id'), 'inline_comments', ['review_session_id'], unique=False)
    op.create_table('usage_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('review_session_id', sa.Integer(), nullable=True),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('estimated_input_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_output_tokens', sa.Integer(), nullable=False),
    sa.Column('gitea_api_calls', sa.Integer(), nullable=False),
    sa.Column('claude_api_calls', sa.Integer(), nullable=False),
    sa.Column('clone_operations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_stats_repository_id'), 'usage_stats', ['repository_id'], unique=False)
    op.create_index(op.f('ix_usage_stats_review_session_id'), 'usage_stats', ['review_session_id'], unique=False)
    op.create_index(op.f('ix_usage_stats_stat_date'), 'usage_stats', ['stat_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_stats_stat_date'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_review_session_id'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_repository_id'), table_name='usage_stats')
    op.drop_table('usage_stats')
    op.drop_index(op.f('ix_inline_comments_review_session_id'), table_name='inline_comments')
    op.drop_table('inline_comments')
    op.drop_index(op.f('ix_review_sessions_repository_id'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_pr_number'), table_name='review_sessions')
    op.drop_table('review_sessions')
    op.drop_index(op.f('ix_model_configs_repository_id'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_repositories_repo_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
